### ISSUE TITLE
LSTFile10 - Call mit 2 Byte Adresse

### ISSUE THREAD

**Issue by WMerk** [zachmann/PicSimulator#8]
Der Call muss eine 2 Byte Adresse bekommen und dann vom Speicher sinnvoll gesetzt werden. Die Anzahl der Befehle in der Datei ist größer als ein Byte.

**Comment by zachmann** [comment]
Sämtliche PCs sind 13 bit Adressen. im Speicher gibt es PCL und PCLATH
